# Generated by Django 5.1.2 on 2024-10-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
